twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
# â€¦
    globals:
        webmaster: "%env(WEBMASTER)%"
    form_themes:
        - 'bootstrap_3_layout.html.twig'